###**8.1. The Deutsch-Jozsa Algorithm**

Deutsch's algorithm is the first algorithm to demonstrate a clear advantage in quantum computing compared to classical computing.

Deutsch's problem is that we have a black box, which computes a one-bit Boolean function. In other words, it is a function that takes one bit and produces one bit as output. For example, this function could represent a routing algorithm, and the output indicates the chosen route (0 or 1).

**Let's explain this statement more simply.**

* Let's say we are interested in a routing algorithm. This algorithm takes a network map consisting of many different routes and selects the best route to reach a specific destination. For example, when a person wants to go from point A to point B, the routing algorithm can show them the shortest or fastest way.

* Now, let's consider this routing algorithm as a "black box". This means that this box takes a starting position as input and specifies the best route as output. This function can be thought of as a one-bit Boolean function because it has only two possible outputs: 0 or 1.

* For example, if a person wants to go from point A to point B, the routing algorithm can give an output of 0 (0: Shortest route). Alternatively, in another direction, it can give an output of 1 indicating that the route is longer or slower (1: Faster route).

Deutsch's problem is to understand the function of this black box. That is, to determine whether this function is constant or balanced. A constant function always gives the same output, while a balanced function produces different outputs depending on the inputs. While this typically requires at least two queries for classical computers, the Deutsch algorithm can determine this function with just one query. This demonstrates the potential acceleration of quantum computers.

Mathematically, when we examine the black box, we can see that there are four different functions that can be obtained from the black box. These are f0, f1, fX, and fX2.

- f0: This is a constant function. That is, it always produces the same output. For example, it can always output 0 regardless of the input.

- f1: This is also a constant function and always produces the same output. For example, it can always output 1 regardless of the input.

- fX: This is a balanced function. That is, it produces different outputs depending on the inputs, but it has an equal number of 0s and 1s in its truth table. For example, the output can be 0 when the input is 0 and can be 1 when the input is 1.

- fX2: This is also a balanced function and has similar properties to fX. It produces different outputs depending on the inputs, but it has an equal number of 0s and 1s in its truth table. For example, the output can be 1 when the input is 0 and can be 0 when the input is 1.

Deutsch's algorithm is used to determine whether this black box function is constant or balanced among these four different functions.

As mentioned above:

- Deutsch's algorithm evaluates the function of this black box and determines whether this function is constant or balanced. A classical computer needs to make at least two queries (for f0 and f1) to solve such a problem. However, the Deutsch algorithm can determine the nature of this function with just one query using **quantum superposition**. This provides a significant speedup compared to classical computers and demonstrates the advantages of quantum computation.

----------------------

**Let's define Deutsch's problem more clearly. As it is now known;**

- Determine whether the function is balanced or constant when given access to a one-bit input and a one-bit output, with as few queries to the function as possible.

----------------------

When approaching the problem with classical tools, we know that we need to query the function at least twice.

**Our queries would be for the following purpose:**

* First, to see the output when the input is 0,
* Then, to see the output when the input is 1.

David Deutsch's remarkable discovery is that only one query is needed, which is possible on a quantum computer. The original Deutsch algorithm deals with a one-bit Boolean oracle case, and the Deutsch-Jozsa algorithm generalizes this approach to handle n-input Boolean functions. Solving an n-bit Boolean function, which requires at least n queries with classical tools, is solved in just one query with the Deutsch-Jozsa algorithm.

----------------------------

**Quantum Advantage Demonstrated by Deutsch-Jozsa**

Classically, distinguishing a constant function from a balanced function requires querying a one-bit Boolean function twice. For an n-bit Boolean function, querying n times is necessary. By using Deutsch-Jozsa on a quantum computer, only one query is sufficient.

------------------------------------

Quantum computers, unlike traditional computers, require reversible operations that map the state of any input to a single outcome. However, some classical functions do not provide this property. For example, constant functions f0 and f1 do not map the result of any input to a specific output and therefore cannot be reversed. To execute such functions on quantum computers, we need to make these operations reversible.

One way to do this is to perform the computation on an additional register or store the inputs in an additional register. For example, let's assume we have an n-bit input x and we compute a (non-reversible) Boolean function f(x). In this case, we can express this operation as a unit acting on n+1 qubits interdependently. This unit allows us to implement the classical function to work with quantum computers.

**Let's illustrate this mathematically:**




   Screenshot 2024-05-05 060348.png


Let's discuss this formula a bit:

* The plus sign inside the circle represents the modulo-2 addition (XOR) operation.

* This function determines how Uf affects all computational basis states (|x) and the single output qubit (|y).

The fact that Uf is defined on the computational basis implies that we can extend the input and output vectors of this operation using the linearity property. This means that Uf is defined across the entire state space.

To see that the transformation is reversible, we can observe that applying Uf twice brings us back to the initial state. This demonstrates that each step of the operation is reversible.

Additionally, it should be noted that Uf maps its orthonormal computational basis onto itself, thus preserving the lengths of the vectors it operates on. This allows Uf to be considered as unitary.

At the heart of this algorithm lies the presence of a superposition state in quantum computers, unlike classical computers that only have two states, 0 and 1. Quantum bits can exist as both 0 and 1 simultaneously. This necessitates the use of a measurement basis that is different from the standard computational basis used when performing computations—known as the Z-basis. This is where the Hadamard basis comes into play. The Hadamard basis represents a state of superposition between 0 and 1. Therefore, measuring in this basis allows us to leverage the quantum advantage because classical computers cannot measure in this basis. This simple change brings out the power of quantum computers and enables certain algorithms to run much faster than classical computers.

###**Now let's do an example with the Deutsch-Jozsa algorithm.**


In [3]:
from qiskit import QuantumCircuit
from qiskit_aer import Aer

# Create a quantum circuit with 2 qubits
qc = QuantumCircuit(2, 1)

# Apply a Hadamard gate to the first qubit
qc.h(0)

# Apply a controlled-NOT gate from the first qubit to the second qubit
qc.cx(0, 1)

# Apply a Hadamard gate to the second qubit
qc.h(1)

# Measure the second qubit
qc.measure(1, 0)

# Print the circuit
print(qc.draw())

# Run the circuit on a simulator
simulator = Aer.get_backend('aer_simulator')
job = simulator.run(qc, shots=1000)
result = job.result()

# Get the counts
counts = result.get_counts()

# Print the counts
print(counts)

     ┌───┐             
q_0: ┤ H ├──■──────────
     └───┘┌─┴─┐┌───┐┌─┐
q_1: ─────┤ X ├┤ H ├┤M├
          └───┘└───┘└╥┘
c: 1/════════════════╩═
                     0 
{'0': 490, '1': 510}


Let's discuss the output above.

**In the first output, we see the circuit we created and its components.**
Here:
* H: Hadamard Gate applies a certain transformation to quantum bits.
* X: Pauli-X gate applies the NOT operation to quantum bits.
* M: Measurement gate resolves the superposition of quantum bits into a result (0 or 1).

**{'1': 510, '0': 490}**

**These are the measurement results. The breakdown is as follows:**

- 510: The number of results where the outcome is 1.
- 490: The number of results where the outcome is 0.
- The total number of measurements is 1000 (as specified by the shots parameter), and the results sum up to 1000 in total.